export const appRoutes = {
  home: '/',
  redirect: '/redirect',
  auth: '/auth',
  admin: {
    profile: '/admin',
    staff: '/admin/all-staff',
    positions: '/admin/positions',
    staffInfo: '/admin/all-staff/profile',
    stats: '/admin/stats',
  },
  employee: {
    profile: '/profile',
    account: '/profile/info',
    dashboard: '/profile/dashboard',
    calendar: '/profile/calendar',
    notes: '/profile/notes',
    teams: '/profile/teams',
    projects: '/profile/projects',
  },
  notFound: '*',
};

export const apiRoutes = {
  users: 'staff',
  google: 'staff/google',
  userInfo: 'staff/info/',
  newUser: 'staff/register-user',
  sessions: 'staff/sessions',
  positions: 'positions',
  newPosition: 'positions/new-position',
  positionById: 'positions/info/',
  editPosition: 'positions/edit/',
  deletePositions: 'positions/delete',
  deleteUser: 'staff/delete/',
  updateUser: 'staff/edit',
  tasks: 'tasks',
  createTask: 'tasks/new-task',
  deleteTask: 'tasks/delete',
  getTask: 'tasks/info',
  editTask: 'tasks/edit/',
};
